backend:
  name: git-gateway
  branch: main    # <-- repo'nun default branch'ine göre 'main' veya 'master' yap

media_folder: "images/uploads"   # repoya kaydedilecek yer
public_folder: "/images/uploads" # web'de erişilecek yol

# JSON dosyası şeklinde products.json kullanıyoruz
collections:
  - name: "products"
    label: "Ürünler"
    files:
      - file: "products.json"
        label: "Products JSON"
        name: "products_json"
        format: json
        fields:
          - { label: "Ürünler", name: "products", widget: "list", collapsed: true, fields:
              - { label: "id", name: "id", widget: "string" }
              - { label: "title", name: "title", widget: "string" }
              - { label: "description", name: "description", widget: "text" }
              - { label: "price", name: "price", widget: "string" }
              - { label: "images", name: "images", widget: "list", collapsed: true, field:
                  { label: "image", name: "image", widget: "image" } }
              - { label: "shopier", name: "shopier", widget: "string" }
            }
